### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by anirbanpalDSC**
Please review the functionalities

### CODE REVIEW

**Comment by Lemonchasers** [comment]
I read through and saw that all of your files have documentation. It looked like you used the PEP257 documentation method. I took a very simple approach to my documentation method and where I wrote simply what was happening. Your documentation seemed very succinct at times and more elaborative at others. Overall, I knew what you were trying to do.

**Review by JonHenin — COMMENTED** [review]
Documentation looks good, seems to follow the correct standards for functions.  For modules, docstrings go at the top of the file, even before the import.  They consist of a general statement about what your module does and an example of how to run the code.  See http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html 
One thing I would mention though is that your modules (scripts) should only have one top-level function in there called main().  The other code either goes in main() or you put helper functions in your util.py, there shouldn't be any other functions called in these files.  See point 4. in the assignment:
4. Implement any helper functions in the msds510.util module. The scripts should only define one top-level function called main.

**Comment by anirbanpalDSC** [comment]
@JonHenin , Thanks for the suggestion. I have implemented the module level doc string and checked in. Because of the project timeline, I am merging this request by I will keep in mind the second suggestion for future changes.

**Comment by krytaylor** [comment]
Anirban, I see that you added the docstrings at the top, so you revised this correctly  so this is good work.

**Pull request merged**
